print("hi")
name=input("Enter your name : ")
name=("name")
print("hello,name")
yourbirthyear =input("Enter yourbirthyear :")
yourbirthyear=int(yourbirthyear)
thisyear=input("Enter thisyear:  ")
thisyear=int(thisyear)
age=thisyear-yourbirthyear
age=int(age)
print("your age is:    ,name")